# templates/customer-tran-generator-job.yaml
{{- $root := . }}
{{- range $file := $root.Values.dataset.files }}
{{- if and (eq $file.name "customer_tran") (gt ($file.dataSize | int) 0) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: customer-tran-generator
  namespace: {{ $root.Values.namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 10
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: customer-tran-generator
          image: python:3.11-slim
          workingDir: /app
          volumeMounts:
            - name: script
              mountPath: /app
            - name: data
              mountPath: {{ $root.Values.dataset.mountPath }}
          env:
            - name: RECORD_COUNT
              value: "{{ $file.dataSize | int }}"
          command:
            - sh
            - -c
          args:
            - |
              pip install faker && \
              python generate_customer_tran.py {{ $root.Values.dataset.mountPath }}/{{ $file.name }}.csv $RECORD_COUNT && \
              echo "✔ Generated $RECORD_COUNT transactions at {{ $root.Values.dataset.mountPath }}/{{ $file.name }}.csv"
      volumes:
        - name: script
          configMap:
            name: customer-tran-generator-script
        - name: data
          persistentVolumeClaim:
            claimName: {{ $root.Values.dataset.pvcName }}
{{- end }}
{{- end }}
