apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.dataset.pvcName }}
  namespace: {{ .Values.namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10000"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
