{{- if .Values.dataset.clearAll}}
apiVersion: batch/v1
kind: Job
metadata:
  name: data-clear-job
  namespace: {{ .Values.namespace }}
  annotations:
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/hook-weight: "-50"
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 10
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: customer-generator
          image: alpine:3.18
          volumeMounts:
            - name: data
              mountPath: {{ .Values.dataset.mountPath }}
          command: ["sh","-c"]
          args:
            - |
              rm -rf /data/*
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.dataset.pvcName }}
{{- end }}
