apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-init-scripts
data:
  init-db.sh: |
    #!/bin/bash
    set -e
    echo "Running initdb.sh"
    # Wait for PostgreSQL to start
    POSTGRES_HOST=localhost
    POSTGRES_USER=postgres
    POSTGRES_DB=postgres
    POSTGRES_PASSWORD=1234

    until pg_isready -h $POSTGRES_HOST -U $POSTGRES_USER
    do
      echo "Waiting for PostgreSQL..."
      sleep 2
    done

    echo "PostgreSQL init-script started!"


    echo "PostgreSQL init-script done!"
