apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql
  namespace: {{ .Values.namespace }}
  annotations:
    field.cattle.io/description: Postgres Volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi