apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-pg-hba-file
data:
  pg_hba.conf: |
    local   all             all                                     scram-sha-256
    host    all             all             127.0.0.1/32            scram-sha-256
    host    all             all             ::1/128                 scram-sha-256
    host    all             all             192.168.1.23/32         scram-sha-256
    host    all             all             0.0.0.0/0               scram-sha-256
