apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-init-scripts
data:
  init-db.sh: |
    #!/bin/bash
    set -e
    echo "Running initdb.sh"

    # Wait for PostgreSQL to start

    until pg_isready
    do
      echo "Waiting for PostgreSQL..."
      sleep 2
    done

    # Temporarily set PGPASSWORD for initial connection
    export PGPASSWORD=${POSTGRES_PASSWORD}

    # Run the SQL script
    psql -h $POSTGRES_HOST -U $POSTGRES_USER -d $POSTGRES_DB -f /docker-entrypoint-initdb.d/init.sql
