{{- if .Values.iceberg.install }}
apiVersion: v1
kind: Service
metadata:
  name: iceberg-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.iceberg.port }}
      targetPort: {{ .Values.iceberg.port }}
      protocol: TCP
  selector:
    app: iceberg
{{- end }}
