{{- if .Values.iceberg.install }}
apiVersion: v1
kind: Secret
metadata:
  name: iceberg-secret
type: Opaque
data:
  iceberg-user: {{ "iceberg" | b64enc }}
  iceberg-password: {{ "test123" | b64enc }}
{{- end }}
