{{- if .Values.iceberg.install }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iceberg
  labels:
    app: iceberg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iceberg
  template:
    metadata:
      labels:
        app: iceberg
    spec:
      securityContext:
        runAsUser: 1001        # Adjust to a proper non-root UID if necessary
        runAsGroup: 1001
        fsGroup: 1001
      containers:
        - name: iceberg
          image: apache/iceberg-rest-fixture  # Update to a valid Iceberg image
          ports:
            - name: iceberg
              containerPort: {{ .Values.iceberg.port }}
              hostPort: {{ .Values.iceberg.port }}
          env:
            - name: ICEBERG_USER
              valueFrom:
                secretKeyRef:
                  name: iceberg-secret
                  key: iceberg-user
            - name: ICEBERG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: iceberg-secret
                  key: iceberg-password
            # --- Added for MinIO Integration ---
            - name: AWS_ACCESS_KEY_ID
              value: "minioadmin"
            - name: AWS_SECRET_ACCESS_KEY
              value: "minioadmin"
            # Set the warehouse directory to the test bucket in MinIO using the S3A scheme
            - name: ICEBERG_WAREHOUSE
              value: "s3a://{{ .Values.minio.testBucketName}}/"
            # Point to the MinIO endpoint; adjust the URL if needed
            - name: S3_ENDPOINT
              value: "http://minio-service:9000"
            # Depending on your Iceberg setup, you might also need to set additional
            # Hadoop or Iceberg configuration parameters via environment variables.
          volumeMounts:
            - name: iceberg-volume
              mountPath: /iceberg/metadata
            - name: iceberg-init-scripts
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: iceberg-volume
          persistentVolumeClaim:
            claimName: iceberg-pvc
        - name: iceberg-init-scripts
          configMap:
            name: iceberg-init-scripts
{{- end }}
