{{- if .Values.superset.install }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: superset-dataset-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  {{- end }}