{{- $root := . }}
{{- range .Values.dataset.files }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: generator-job-{{ .configMapName }}
  namespace: {{ $.Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "{{ mul 10 .rank }}"
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 10
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: {{ .configMapName }}
          image: python:3.11-slim
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
          command: ["/bin/sh", "-c"]
          args:
            - >
              pip install Faker numpy && exec python3 /scripts/{{ .configMapName }}/{{ .configMapName }}.py \
                "{{ $.Values.dataset.mountPath }}/{{ .fileName }}" \
                "{{ .dataSize }}" \
                --workers "{{ $.Values.script.workers }}"{{ if .masterDsName }} \
                --master "{{ $.Values.dataset.mountPath }}/{{ .masterDsName }}"{{ end }}
          volumeMounts:
            - name: data
              mountPath: {{ $.Values.dataset.mountPath }}
            - name: {{ .configMapName }}
              mountPath: /scripts/{{ .configMapName }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ $.Values.dataset.pvcName }}
        - name: {{ .configMapName }}
          configMap:
            name: {{ .configMapName }}
{{- end }}