{{- if .Values.minio.install }}
apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  type: NodePort
  ports:
    - name: minio-api
      port: 9000
      targetPort: 9000
      nodePort: 30000
    - name: minio-console
      port: 9001
      targetPort: 9001
      nodePort: 30001
  selector:
    app: minio
{{- end }}
