{{- if .Values.minio.install }}
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
data:
  minio-root-user: {{ "minioadmin" | b64enc }}
  minio-root-password: {{ "minioadmin" | b64enc }}
{{- end }}
