{{- if .Values.db.postgresql.install }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "postgresql"
  namespace: {{ .Values.namespace }}
  labels:
    app: "postgres"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "postgres"
  template:
    metadata:
      labels:
        app: "postgres"
    spec:
      containers:
        - name: postgresql
          image: "bitnami/postgresql"
          securityContext:
            runAsUser: 0
          env:
            - name: PGPORT
              value: "{{ .Values.db.postgresql.port }}"
            - name: PGUSER
              value: "{{ .Values.db.postgresql.users.root.username }}"
            - name: POSTGRESQL_PASSWORD
              value: "{{ .Values.db.postgresql.users.root.password }}"
            - name: DB_NAME
              value: "{{ .Values.db.postgresql.testdb.name }}"
            - name: ALLOW_EMPTY_PASSWORD
              value: "no"
            - name: PGLOAD_PARALLEL
              value: '{{ .Values.dataset.loadParallelism | default "$(nproc)" }}'
          ports:
            - name: postgresql
              containerPort: {{ .Values.db.postgresql.port }}
          resources:
            requests:
              cpu: "4"
              memory: "32Gi"
            limits:
              cpu: "4"
              memory: "32Gi"
          volumeMounts:
            - name: postgresql-config
              mountPath: /bitnami/postgresql/conf/postgresql.conf
              subPath: postgresql.conf
            - name: data
              mountPath: /bitnami/postgresql
              readOnly: false
            - name: postgresql-init-scripts
              mountPath: /docker-entrypoint-initdb.d
            - name: dataset-pvc
              mountPath: {{ .Values.dataset.mountPath }}
            - name: postgresql-pg-hba-file
              mountPath: /bitnami/postgresql/conf/pg_hba.conf
              subPath: pg_hba.conf
      volumes:
        - name: postgresql-config
          configMap:
            name: postgresql-config
        - name: data
          persistentVolumeClaim:
            claimName: postgresql-pvc
        - name: postgresql-init-scripts
          configMap:
            name: postgresql-init-scripts
        - name: dataset-pvc
          persistentVolumeClaim:
            claimName: dataset-pvc
        - name: postgresql-pg-hba-file
          configMap:
            name: postgresql-pg-hba-config
            defaultMode: 0644
            items:
              - key: pg_hba.conf
                path: pg_hba.conf
{{- end }}