{{- if .Values.db.postgresql.install }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
  namespace: {{ .Values.namespace }}
  annotations:
    field.cattle.io/description: Postgres Volume
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/hook-weight: "-100"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
{{- end }}