{{- if .Values.db.postgresql.install }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "postgresql"
  namespace: {{ .Values.namespace}}
  labels:
    app: "postgres"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "postgres"
  template:
    metadata:
      labels:
        app: "postgres"
    spec:
      containers:
        - name: postgresql
          image: "bitnami/postgresql"
          securityContext:
            runAsUser: 0
          env:
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: postgresql-password
          ports:
            - name: postgresql
              containerPort: {{ .Values.db.postgresql.port }}
          volumeMounts:
            - name: data
              mountPath: /bitnami/postgresql
              readOnly: false
            - name: postgresql-init-scripts
              mountPath: /docker-entrypoint-initdb.d
            - mountPath: /{{ .Values.datasets.mountPath }}
              name: dataset-pvc
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgresql-pvc
        - name: postgresql-init-scripts
          configMap:
            name: postgresql-init-scripts
        - name: postgresql-pg-hba-file
          configMap:
            name: postgresql-pg-hba-file
        - name: dataset-pvc
          persistentVolumeClaim:
            claimName: dataset-pvc
{{- end }}
