{{- if .Values.db.postgresql.install }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.postgresql.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: "postgres"
{{- end }}