{{- if .Values.db.postgresql.install }}
apiVersion: v1
kind: Secret
metadata:
  name: "postgresql"
  namespace: {{ .Values.namespace }}
data:
  postgresql-username: {{ .Values.db.postgresql.root.username  | b64enc| quote }}
  postgresql-password: {{ .Values.db.postgresql.root.password  | b64enc| quote }}
  postgresql-database: {{ .Values.db.postgresql.root.database  | b64enc| quote }}
  {{- end }}