{{- if .Values.db.postgresql.install }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "postgresql"
  namespace: {{ .Values.namespace}}
  labels:
    app: "postgres"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "postgres"
  template:
    metadata:
      labels:
        app: "postgres"
    spec:
      containers:
        - name: postgresql
          image: "bitnami/postgresql"
          securityContext:
            runAsUser: 0
          env:
            - name: POSTGRESQL_PASSWORD
              value: "{{ .Values.db.postgresql.users.root.password }}"
          ports:
            - name: postgresql
              containerPort: {{ .Values.db.postgresql.port }}
          volumeMounts:
            - name: data
              mountPath: /bitnami/postgresql
              readOnly: false
            - name: postgresql-init-scripts
              mountPath: /docker-entrypoint-initdb.d
            - mountPath: /{{ .Values.dataset.mountPath }}
              name: dataset-pvc
            - name: postgresql-pg-hba-file
              mountPath: /opt/bitnami/postgresql/conf/pg_hba.conf
              subPath: pg_hba.conf
              readOnly: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgresql-pvc
        - name: postgresql-init-scripts
          configMap:
            name: postgresql-init-scripts
        - name: dataset-pvc
          persistentVolumeClaim:
            claimName: dataset-pvc
        - name: postgresql-pg-hba-file
          configMap:
            name: postgresql-pg-hba-config
            items:
              - key: pg_hba.conf
                path: pg_hba.conf
{{- end }}
