{{- if .Values.db.postgresql.install }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.postgresql.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
      - port: {{ .Values.db.postgresql.port }}
        targetPort: postgresql
        nodePort: 30032  # Choose a port in the range 30000-32767
  type: NodePort
  selector:
    app: "postgres"
{{- end }}