{{- if .Values.hudi.install }}
apiVersion: v1
kind: Service
metadata:
  name: hudi-service
spec:
  selector:
    app: hudi
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
{{- end }}