{{- if .Values.hudi.install }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hudi
  labels:
    app: hudi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hudi
  template:
    metadata:
      labels:
        app: hudi
    spec:
      containers:
        - name: hudi
          image: apache/hudi:0.14.0-spark3.3
          command: ["/bin/bash", "/docker-entrypoint-initdb.d/init-db.sh"]
          volumeMounts:
            - mountPath: /{{ .Values.dataset.mountPath }}
              name: dataset-pvc
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: dataset-pvc
          persistentVolumeClaim:
            claimName: dataset-pvc
        - name: init-scripts
          configMap:
            name: hudi-init-scripts
{{- end }}
