namespace: "affixzone-test-containers"
testPvc: false
testPod: true
dataset:
  mountPath: "/datasets"
  pvcName: "dataset-pvc"
  clearAll: false
  files:
    - configMapName: customer-generator-script
      fileName: "customer_100k.csv"
      dataSize: 100000
      rank: 1
    - configMapName: customer-tran-generator-script
      fileName: "customer_tran_100k.csv"
      masterDsName: "customer_100k.csv"
      dataSize: 100000
      rank: 2
    - configMapName: customer-tran-generator-script
      fileName: "customer_tran_1m.csv"
      masterDsName: "customer_100k.csv"
      dataSize: 1000000
      rank: 2
    - configMapName: customer-tran-generator-script
      fileName: "customer_tran_10m.csv"
      masterDsName: "customer_100k.csv"
      dataSize: 10000000
      rank: 3
    - configMapName: customer-tran-generator-script
      fileName: "customer_tran_100m.csv"
      masterDsName: "customer_100k.csv"
      dataSize: 100000000
      rank: 3
script:
  workers: 16