{{- if .Values.db.cassandra.install }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.cassandra.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - name: cassandra-port-9042   # Added a unique name for port 9042
      port: 9042
      targetPort: 9042
  selector:
    app: "cassandra"
{{- end }}